spring.profiles.active: production

spring.thymeleaf.cache: false
spring.web.host: http://www.liquidrubber-diy.com.tw
spring.web.name: 液態橡膠
server.port: 80
spring.security.user.name: user
spring.security.user.password: user

spring.session.store-type: none
spring.h2.console.enabled: true
spring.jpa.open-in-view: false

spring:
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mail:
    username: yuanta.ecp@gmail.com
    #liquidrubbertaiwan@gmail.com
    password: s@700315
    #baby0126
    host: smtp.gmail.com
    port: 587
    from: cyliu0315@gmail.com
      
logging:
  level:
    org.springframework.security.web.context: ERROR
    #org.springframework.security: DEBUG
    #org.springframework.security.web.context: ERROR
    #org.springframework.web: DEBUG
    #guru.springframework.controllers: DEBUG
    #org.hibernate: DEBUG
spring.batch.job.enabled: false

payment.creditcard.storeId: 62253
#自動請款標記 1: 自動請款 0: 一般交易
payment.creditcard.depositFlag: 0
#查詢標記 1: 交易post回UpdateUrl
payment.creditcard.queryFlag: 1
#get回傳頁
payment.creditcard.returnURL: ${spring.web.host}/payment/payment_receive/creditcard
#post回傳頁
payment.creditcard.updateURL: ${spring.web.host}/payment/payment_receive/creditcard

shopping.currency: NTD
server.image.path: /home/ubuntu/ShoppingCart/files
