spring.profiles.active: production

spring.thymeleaf.cache: false
spring.web.host: http://localhost:8090
spring.web.name: 液態橡膠
server.port: 8090
spring.security.user.name: user
spring.security.user.password: user

spring.session.store-type: none
spring.h2.console.enabled: true
spring.jpa.open-in-view: false

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/SHOPPING_CART
    username: liquidrubber
    password: liquidrubber123
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mail:
    username: yuanta.ecp@gmail.com
    #liquidrubbertaiwan@gmail.com
    password: s@700315
    #baby0126
    host: smtp.gmail.com
    port: 587
    from: liquidrubbertaiwan@gmail.com
      
logging:
  level:
    org.springframework.security.web.context: ERROR
    #org.springframework.security: DEBUG
    #org.springframework.security.web.context: ERROR
    #org.springframework.web: DEBUG
    #guru.springframework.controllers: DEBUG
    #org.hibernate: DEBUG
spring.batch.job.enabled: false

payment.creditcard.storeId: 62253
#自動請款標記 1: 自動請款 0: 一般交易
payment.creditcard.depositFlag: 0
#查詢標記 1: 交易post回UpdateUrl
payment.creditcard.queryFlag: 1
#get回傳頁
payment.creditcard.returnURL: ${spring.web.host}/payment/payment_receive/creditcard
#post回傳頁
payment.creditcard.updateURL: ${spring.web.host}/payment/payment_receive/creditcard

shopping.currency: NTD
shopping.currency.tw: 新台幣
server.image.path: D:/Private/Shopping/ShoppingCart/files
shopping.bankcode: 822(中國信託銀行代碼)
shopping.accountNo: 1235675432355
shopping.accountName: 築城國際事業有限公司
